# Generated by Django 5.1.5 on 2025-02-27 10:02

import django.db.models.deletion
import django.utils.crypto
import functools
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=functools.partial(django.utils.crypto.get_random_string, *(100,), **{}), max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
