# Generated by Django 5.1.4 on 2025-01-31 13:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_cafe_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('drinks', 'drinks'), ('main_dishes', 'main_dishes'), ('dessert', 'dessert'), ('fast_food', 'fast_food')], max_length=20),
        ),
    ]
